# Generated by cpp11: do not edit by hand

header_to_fwf_position_cpp <- function(start_end, left_justified, read_only) {
  .Call(`_DSSAT_header_to_fwf_position_cpp`, start_end, left_justified, read_only)
}
