# Generated by cpp11: do not edit by hand

de_regex <- function(the_regex) {
  .Call(`_DSSATcpp_de_regex`, the_regex)
}

extract_names <- function(header, col_types, ljust, col_names) {
  .Call(`_DSSATcpp_extract_names`, header, col_types, ljust, col_names)
}

gen_regex <- function(cnames, ljust) {
  .Call(`_DSSATcpp_gen_regex`, cnames, ljust)
}

header_to_fwf_position_cpp <- function(header, col_types_names, left_justified, col_names_in, read_only) {
  .Call(`_DSSATcpp_header_to_fwf_position_cpp`, header, col_types_names, left_justified, col_names_in, read_only)
}

name_to_regex <- function(cnames) {
  .Call(`_DSSATcpp_name_to_regex`, cnames)
}
